name: Cypress tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests-chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository goit-cy-hw-03
        uses: actions/checkout@v3
      
      - name: Install Dependensies goit-cy-hw-03
        uses: npm install

      - name: Run Cypress Tests goit-cy-hw-03
        uses: npm run cypress:run:chrome
